### ISSUE TITLE
I suggest that instead of 35%, the chart should say 1.35x

### ISSUE THREAD

**Issue by daveyostcom** [wadefagen/91-DIVOC#14]
Much clearer.

**Comment by daveyostcom** [comment]
Also, the 1.35x is on a dotted line all the way from 0,0 up and to the right, suggesting that being under that line to be better than 1.35x, but really, being at a shallower angle than that line is better, no matter how far up or over you are on the curve. So I suggest that you show the 1.35x line in a separate Key area, say, upper left, perhaps with a couple of other lines, including a horizontal line showing 1x and calling that out as "no change" (for those just getting familiar with a log graph).

**Comment by chetmurthy** [comment]
Hi, it seems like maybe it might be useful to have a line for 1.2x, just so people can get a better estimate of  the growth rate of the many lines that are below 1.35x.

**Comment by daveyostcom** [comment]
> Hi, it seems like maybe it might be useful to have a line for 1.2x, just so people can get a better estimate of the growth rate of the many lines that are below 1.35x.

similar to the way Angela Merkel just explained it.
https://twitter.com/QuickTake/status/1250754686375931904

**Comment by daveyostcom** [comment]
btw, thanks for making the change!
