### ISSUE TITLE
days since n  vs  absolute date

### ISSUE THREAD

**Issue by daveyostcom** [wadefagen/91-DIVOC#16]
The graphs currently show days since n, which is useful. But it would be even better if this were a checkbox. When the Days since N checkbox is off, then the x axis would be the absolute date.

A text field for n would also be interesting.

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page. Moving to managing this issues on github and using best practices here, sorry for missing this!

A bit after you posted this, I added an "X-Axis" feature that did something very similar -- you can "left align" it to a threshold or "right align" it to the current date.  For example, here is right-aligned data: https://91-divoc.com/pages/covid-visualization/?chart=countries&highlight=United%20States&show=25&y=both&scale=linear&data=cases-daily-7&data-source=jhu&xaxis=right#countries
