### ISSUE TITLE
I created a Canadian Version - issue not an issue

### ISSUE THREAD

**Issue by esklarski** [wadefagen/91-DIVOC#17]
I'm too far removed to create a fork of this project but wanted to inform of my "fork".

With a few modifications I have created a Canadian version of this web page, displaying provinces instead of states.

I have put it  up on Github Pages:
https://esklarski.github.io/canada.covid19/

and my code is here:
https://github.com/esklarski/canada.covid19

Thanks for sharing your code!

**Comment by varnav** [comment]
If you hover over a dot it still shows mm-dd-yyyy date format.

**Comment by esklarski** [comment]
fixed

thanks for pointing that out

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page. Moving to managing this issues on github and using best practices here, sorry for missing this!

OOO, beautiful, and I'll try and find a place to link to your derived work! :)
