### ISSUE TITLE
Feature request: Add date to data point tooltip

### ISSUE THREAD

**Issue by shirriff** [wadefagen/91-DIVOC#26]
It would be nice to add the actual date in the tooltip. This would help correlate points on the curve to real-world events.

Observed behavior: tooltip says "Day 17"
Requested behavior: tooltip also says "March 23" or whatever the date should be.

![image](https://user-images.githubusercontent.com/188116/78713099-906ed480-78ce-11ea-8e08-1f9b7066b8c7.png)

(The website is very cool and provides information that I couldn't find anywhere else.)

**Comment by wangzang** [comment]
The date **is** in the tooltip. In your screenshot, it says "163 confirmed cases per 1,000,000 people on **03-24-2020**. For some reason, I didn't see this myself too. I only noticed it when I started looking for the associated code, by looking at the text more carefully.

**Comment by shirriff** [comment]
Closing issue because submitter is a bonehead :-)
