### ISSUE TITLE
Feature Request: Logistic Curve Trend line

### ISSUE THREAD

**Issue by flbuddymooreiv** [wadefagen/91-DIVOC#29]
Since you have got an exponential curve trend line, perhaps it would be interesting to attempt to fit the data onto an logistic curve as this is the real model by which infection follows.

**Comment by flbuddymooreiv** [comment]
Here is a library for calculating a function to plot.

https://github.com/mljs/logistic-regression

**Comment by danie906** [comment]
I would fit the last 21 days and use that to project the next 7 days.
from scipy.optimize import curve_fit
x = np.array([N-21:N])
xx = np.array([N:N+7])
def func(x, a, b, c, d):
    return a*np.exp(-c*(x-b))+d
popt, pcov = curve_fit(func, x, y, [1,1,1e-6,1])
yy = func(xx, *popt)

But I like the idea of using a logistic fit too.

**Comment by wadefagen** [comment]
The trendlines ended up being extremely misleading and didn't work as I intended -- they were quickly dropped and the only bit that remains is one that shows a relative linear/log scale starting at the (0,0) point.
