### ISSUE TITLE
Graphs do not reflect select

### ISSUE THREAD

**Issue by tobes** [wadefagen/91-DIVOC#32]
Thanks for this great visualization - I have a small usability issue

When the page is refreshed graphs and the select options do not match. FF75, linux

Please either force the selects to the default or use the values in the select to draw the graphs.

**Comment by pricelessbrewing** [comment]
Happening here as well on Firefox, chrome, windows 10 and chrome android 10. All up to date

**Comment by tobes** [comment]
I did a fix #38 but seeing as the code here hasn't been updated in a while but the website has been I think this repo may be dead

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page. Moving to managing this issues on github, sorry for missing this!

This ended up being something that was tricky to finally get fixed completely.  Firefox, Chrome, and Safari all have slightly different behavior when using back, forward, and refresh buttons -- some retain all the state, some retain the variables but re-executes the JS, some will trigger onChange events and others won't.

Through a bunch of different changes, I think this is fixed for good. :)
