### ISSUE TITLE
#01: indicate when stay at home orders, wear mask orders, etc. went in to effect

### ISSUE THREAD

**Issue by bbodenmiller** [wadefagen/91-DIVOC#35]
Some states appear equal up until a certain point when normalized. Would be cool to see when various distancing measures went in to effect to try and draw some basic correlations.

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page. Moving to managing this issues on github, sorry for missing this!

One thing I've tried to keep 91-DIVOC is "just the data".  Unfortunately, the patchwork of easing stay-at-home orders has made any data related to this extremely messy and I imagine there will be researchers years from now exploring the impact that various degrees of lifting these stay-at-home orders might have contributed to the "second wave"... I cannot image how to add this nowdays.

Thanks for taking the time to make the suggestion! :)
