### ISSUE TITLE
Feature request: allow adding sub-national regions to nations

### ISSUE THREAD

**Issue by taterkerman** [wadefagen/91-DIVOC#37]
Subject sort of says it all. It might be useful to compare (with the same start date thresholds ) a State to a county, for example. The alternative would be able to add countries together (like what does the EU look like compared to the US, for example).

Thanks for a great visualization tool!

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page. Moving to managing this issues on github, sorry for missing this!

Soon after your comment, I added a feature that you can "Add U.S. State" to the visualization of countries.  You can visualize Texas vs. the EU, for example.  Here's an example of exactly that: https://91-divoc.com/pages/covid-visualization/?chart=countries&highlight=European%20Union&show=25&y=highlight&scale=linear&data=cases-daily-7&data-source=jhu&xaxis=right&extra=Texas#countries

**Comment by taterkerman** [comment]
No worries, you were busy, I’ve been following, thx!

Merrick
