### ISSUE TITLE
Feature Request: Normalize by 100,000 instead of 1,000,000

### ISSUE THREAD

**Issue by filmo** [wadefagen/91-DIVOC#39]
For state level graphs numerical stability would be better if normalized by 'per 100,000' rather than by '1e6'

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page. Moving to managing this issues on github, sorry for missing this!

I initially picked cases /1m as the numbers were so small that cases /100k would result in many areas with value below 1.0.  Sadly, it's almost like we need cases /10k now. :(

However, they're easy to mentally convert between units and there's something about 1m that seems "nice" (at least to me).
