### ISSUE TITLE
Please add South Africa to population normalized graph

### ISSUE THREAD

**Issue by warwickchapman** [wadefagen/91-DIVOC#4]
Please add South Africa to population normalized graph!

Our lockdown start tomorrow midnight.

**Comment by giiba** [comment]
It is more than just South Africa, Canada is the one I noticed first. It seems there are many countries not being added to the 'Highlight' option for the population graph.

I've dug around in the code a bit but can see no reason some countries are excluded from this list as there is wikipedia data in the .csv file for both of these places and yet they do not appear.

**Comment by giiba** [comment]
South Africa and everywhere else is available. I think we were just missing the obvious. If you select 'All' from the 'Show' select the missing countries appear as options and you can view the data.

I am still unsure of how the filter works though 😎
