### ISSUE TITLE
Mortality rate: plot new deaths with 2 weeks lag from new confirmed cases

### ISSUE THREAD

**Issue by scriptin** [wadefagen/91-DIVOC#41]
The idea is to plot a ratio of deaths against the new confirmed cases with a 2 weeks lag, or whatever the current known average "from infection until death" time span is. Basically, to show mortality rates among those who get infected on each particular day.

The expected behavior is that there will be an almost horizontal line (probably only when smoothed), potentially with a "hill" where there are too many people sick at once and a health system has no more capacity to handle this surge.

I read claims that because of different countries counting deaths differently (some even suspect hiding the actual number of deaths in some non-democratic countries), we see differences in numbers. While this graph would not reveal the reasons for differences, it can potentially show surges in mortality rates, indicating that health systems' capacities have been exceeded.

**Comment by sigmaxipi** [comment]
You can get some of this info now if you bring up a console and type `document.getElementsByTagName('select')[1].add(new Option('Daily Mortality Rate', 'mortalityRate-daily'))`. That adds a new option to get `daily deaths / daily cases`. I looked at `covid-visualization/vis.js` to see if there was an easy way to get a `weekly average of (daily deaths / daily cases)`, but I could only get it to give me `average(cumulative mortality)` which isn't useful. There may be an easy way to get a proper average and add a lag.

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page. Moving to managing this issues on github and using best practices here, sorry for missing this!

This was a brilliant console hack for it and this feature has been added to the visualization without needing the console hack. :)
- Case Fatality Rate, 1 week: https://91-divoc.com/pages/covid-visualization/?chart=countries&highlight=United%20States&show=25&y=both&scale=linear&data=mortalityRate-daily-7&data-source=jhu&xaxis=right#countries
- Case Fatality Rate, 1 month: https://91-divoc.com/pages/covid-visualization/?chart=countries&highlight=United%20States&show=25&y=both&scale=linear&data=mortalityRate-daily-30&data-source=jhu&xaxis=right#countries
