### ISSUE TITLE
feature request: new cases as a percentage of tests

### ISSUE THREAD

**Issue by danielskatz** [wadefagen/91-DIVOC#42]
It would be useful to have an option to see the number of new cases as a percentage of tests. This could be shown on a daily basis, and with a 7 day average

**Comment by wadefagen** [comment]
Hi Daniel, I've been a fan of your work -- for quite some time, I mostly handled response by e-mail and didn't use this issues page.  Moving to managing this issues on github and following best practices for OSS, sorry for missing this!

Soon after you made the comment, I added "Test Positivity" that displays (total cases) / (total tests) and is as a cumulative total, a one-day value, and a 7-day average.  For example, here's a 7-day chart: https://91-divoc.com/pages/covid-visualization/?chart=countries&highlight=United%20States&show=25&y=highlight&scale=linear&data=testPositivity-daily-7&data-source=merged&xaxis=left#countries

**Comment by danielskatz** [comment]
thanks
