### ISSUE TITLE
mouseover effects

### ISSUE THREAD

**Issue by daveyostcom** [wadefagen/91-DIVOC#44]
When I mouseover a data point, I get a tooltip. Thanks.

It also would be nice if all of the points for the state would be highlighted on mouseover.

Clicking should change the selection.

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page.  Moving to managing this issues on github, sorry for missing this!

That said, this feature was implemented soon after your suggestion and you'll see it on the visualization: https://91-divoc.com/pages/covid-visualization/ :)

**Comment by daveyostcom** [comment]
The mouse-over feature works, thanks!
Also, clicking could change the selection to the moused-over curve.

**Comment by daveyostcom** [comment]
Mouse-over on the name at right would be good, too.
