### ISSUE TITLE
Per state graphs for countries other than the US

### ISSUE THREAD

**Issue by ElminsterAU** [wadefagen/91-DIVOC#45]
Seeing that `time_series_covid19_confirmed_global.csv` (and deaths and recovered) include per state data for a number of countries outside the US, would you please consider adding a "country" dropdown to the "by US States/Territories per Day" graph where you can select one of the countries that has per state data?

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page.  Moving to managing this issues on github, sorry for missing this!

I ended up implementing the inverse of that feature, where you can add states to the US country graph -- you'll see it on the visualization: https://91-divoc.com/pages/covid-visualization/ :)

**Comment by ElminsterAU** [comment]
Ah, that's unfortunately not what I meant.

I would like to be able to compare e.g. Queensland vs NSW vs Victoria (all Australian states which for which separate numbers are provided in `time_series_covid19_confirmed_global.csv`)
