### ISSUE TITLE
Y-axis scale to highlight, takes into account out-of-window data

### ISSUE THREAD

**Issue by ernest-tg** [wadefagen/91-DIVOC#46]
Scale to highlight takes into account all data points of the highlighted states. But, when using right-align, some of the data may be out of the window.

This means that it's hard to see current variations for data which values have decreased a lot since their global maximum. For instance:

-  deaths in NY: https://91-divoc.com/pages/covid-visualization/?chart=states-normalized&highlight=New%20York&show=highlight-only&y=highlight&scale=linear&data=deaths-daily-7&xaxis=right-4wk#states-normalized
- cases in MT: https://91-divoc.com/pages/covid-visualization/?chart=states-normalized&highlight=New%20York&show=highlight-only&y=highlight&scale=linear&data=deaths-daily-7&xaxis=right-4wk#states-normalized

This issue will be increasingly important as more state/countries squash their epidemy (hopefully). 

This problem also impacts visualization of test positivity, since some states had very noisy data in the early stage of the epidemics. The best example is probably California: 
https://91-divoc.com/pages/covid-visualization/?chart=states&highlight=California&show=highlight-only&y=highlight&scale=linear&data=testPositivity-daily-7&xaxis=right-4wk#states 

This could also be mitigated if the user could select the bound of the y-axis themselves.

As always, thanks for making such a great tool available for free!

**Comment by wadefagen** [comment]
Thank you for the fantastic and detailed report with links!  The scope of the data is now checked before the max y-axis scale is determined that fixes all of those graphs and will be deployed in a few minutes! :)
