### ISSUE TITLE
Feature request: Plot percentage change per day per country

### ISSUE THREAD

**Issue by abaybas-clapfoot** [wadefagen/91-DIVOC#48]
Instead of absolute numbers or population normalized values, it'd be useful to see percentage change values for each day.

The vertical bar might show the range -20% to 50%, and one might notice some countries are grouping around 2-3% daily change while other countries might be doing better or worse.

Thanks for this super useful tool.

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page. Moving to managing this issues on github, sorry for missing this!

I tried implementing this, but the underlying data is so messy on anything but a 7-day average that there's massive one-day swings.  Instead, I added a "Generate Report" that lists those in a textual way that still allows exploration of the largest growing (and largest shrinking) state/country of any specific data source.

For example, this report will show which states have the largest increase in raw numbers and percentage of new COVID-19 cases, averaged over the past 7 days: https://91-divoc.com/pages/covid-visualization/?chart=states&highlight=California&show=us-states&y=both&scale=linear&data=cases-daily-7&data-source=jhu&xaxis=right#states
