### ISSUE TITLE
Highlight==None results in broken graph

### ISSUE THREAD

**Issue by bartgrantham** [wadefagen/91-DIVOC#49]
On this page: http://91-divoc.com/pages/covid-visualization/

It looks like the y-axis goes to a default very small scale so all the data is clamped to the top edge of the graph.  This is resolved by setting the y-axis manually, but it defaults to "Scale to Highlight and Cur. Max".

I suggest that if the y-axis is set to **Scale to Highlight and Cur. Max** and the user sets the highlight to **None**, you should automatically change the y-axis to **Fixed**.

**Comment by wadefagen** [comment]
Thanks for the bug report!  I didn't keep up with the issues page and, instead, focused on e-mail, but now using better practices and running it much more via git.

I did a few tests and i believe this is fixed. :)
