### ISSUE TITLE
Could you add days since lock down/stay at home orders (or some measure of preventative action)? Or maybe color code or allow a hinge in a fit line? 

### ISSUE THREAD

**Issue by MichelleDBG** [wadefagen/91-DIVOC#5]

**Comment by wadefagen** [comment]
For quite some time, I mostly handled response by e-mail and didn't use this issues page. Moving to managing this issues on github, sorry for missing this!

One thing I've tried to keep 91-DIVOC is "just the data". Unfortunately, the patchwork of easing stay-at-home orders has made any data related to this extremely messy and I imagine there will be researchers years from now exploring the impact that various degrees of lifting these stay-at-home orders might have contributed to the "second wave"... I cannot image how to add this nowdays.

Thanks for taking the time to make the suggestion! :)
