### ISSUE TITLE
Feature request: display at least 2 significant digits (when hovering on data point)

### ISSUE THREAD

**Issue by ernest-tg** [wadefagen/91-DIVOC#51]
When I monitor the deaths in the European Union, normalized by population, it is hard to see if it's going up or down. The average has been 0.2 for the last few weeks. But that could be anything from 0.151 to 0.249. So, a constant number could hide the fact that deaths halved or doubled in the last few weeks.

The more successful a country, the more noticeable the problem: for Japan, the graph says 0 deaths/1m inhabitant even though it's non-zero (closer to 0.001).

**Comment by wadefagen** [comment]
Fantastic suggestion -- thank you! 🎉

I've modified the mouseover code to inspect the numbers and give an appropriate number of decimal places based on the magnitude of the data.  This will be out as part of the next release (later tonight or early tomorrow)! :)

**Comment by ernest-tg** [comment]
Awesome! Thanks for doing it so quickly :)
