### ISSUE TITLE
Add risk levels to per-capita graphs

### ISSUE THREAD

**Issue by MiguelVieira** [wadefagen/91-DIVOC#53]
Risk levels here: https://globalepidemics.org/key-metrics-for-covid-suppression/
- Green: < 1 case / 100k
- Yellow: 1 to 10 cases / 100k
- Orange: 10 to 25 cases / 100k
- Red: > 25 cases / 100k

**Comment by wadefagen** [comment]
There's a lot of great risk-level visualizations out there and I don't the real value of 91-DIVOC is that "it's just the raw data" -- no modeling, no prediction, just data.  I plan to keep 91-DIVOC that way so won't be adding anything like risk levels.

However, thanks for the great suggestion! :)
