### ISSUE TITLE
secondary axis using "additional data" mixes datasets using national + state

### ISSUE THREAD

**Issue by jasonbuechler** [wadefagen/91-DIVOC#54]
**This is kind of complicated so I'll keep the text description short and let the screenshots do the explaining.**

I think there's a bug in how...
* secondary axis data is mis-labeled, in this instance
* incorrectly labeled secondary series seems wrong or maybe normalized using primary series' datum?
...while comparing both cases, and deaths, for the US as a whole, plus Arizona

**Parameters for this setup:**
http://91-divoc.com/pages/covid-visualization/?chart=countries-normalized&highlight=United%20States&show=highlight-only&y=both&scale=linear&data=deaths-daily-7&data-source=jhu&xaxis=right-8wk&extra=Arizona&extraData=cases-daily-7&extraDataScale=separately#countries-normalized

USA&AZ: [new deaths; new cases] (normalized; 7d avg)
![image](https://user-images.githubusercontent.com/34217071/87982880-5647ce00-ca8c-11ea-8dce-1e08cab8deac.png)

**The individual charts for deaths and cases are as follows:**

USA&AZ: new deaths (normalized; 7d avg)
![image](https://user-images.githubusercontent.com/34217071/87982500-bf7b1180-ca8b-11ea-804a-8f89f73d5b61.png)

USA&AZ: new cases (normalized; 7d avg)
![image](https://user-images.githubusercontent.com/34217071/87982380-93f82700-ca8b-11ea-8cd3-1d1e392d2b38.png)

**Comment by wadefagen** [comment]
Thanks for this detailed report -- this is tricky and deep.  It appears isolated only to when using `subdata` (ex: state-level data) on the country level map.  Should have a fix tonight or tomorrow. :)

**Comment by wadefagen** [comment]
Thanks for the bug report, it's now fixed and deployed. 🎉

**Comment by jasonbuechler** [comment]
sweet! thanks for your hard work, and great product!
