### ISSUE TITLE
Total Active Cases are missing in some countries

### ISSUE THREAD

**Issue by AceChenX** [wadefagen/91-DIVOC#55]
Some countries are missing [Total Active Cases](https://91-divoc.com/pages/covid-visualization/?chart=countries&highlight=Taiwan&show=-10&y=fixed&scale=linear&data=active&data-source=jhu&xaxis=right-all#countries) updates after their numbers dropped down to ~ 100.

**Comment by wadefagen** [comment]
Thanks for the bug report -- the data should never stop being recorded after the cases reach the threshold!  The latest update is live. :)
