### ISSUE TITLE
Animate for states bug: Uncaught TypeError: Cannot read property 'cases' of undefined

### ISSUE THREAD

**Issue by TheeMattOliver** [wadefagen/91-DIVOC#56]
Animation doesn't work on New Confirmed COVID-19 Cases per Day by US States/Territories 

At http://91-divoc.com/pages/covid-visualization/ when trying to animate the New Confirmed COVID-19 Cases per Day by US States/Territories, console throws error: Uncaught TypeError: Cannot read property 'cases' of undefined

Happens for every state but some examples:

http://91-divoc.com/pages/covid-visualization/?chart=states&highlight=Minnesota&show=us-states&y=both&scale=linear&data=cases-daily-7&data-source=jhu&xaxis=right#states

http://91-divoc.com/pages/covid-visualization/?chart=states&highlight=Arkansas&show=us-states&y=both&scale=linear&data=cases-daily-7&data-source=jhu&xaxis=right#states

**Comment by wadefagen** [comment]
Thanks for the bug report -- I just applied a fix.  This broken with an update to improve the label layout and some labels were being considered that had no data attached to them.

The update is live on 91-DIVOC. :)
