### ISSUE TITLE
Line color changes during animation 

### ISSUE THREAD

**Issue by kidinthehall** [wadefagen/91-DIVOC#57]
During the animate function, the legend color seems to stay with the highest-ranked data point instead of staying consistent across the simulation.

![image](https://user-images.githubusercontent.com/12635915/88946373-2e5f2400-d25d-11ea-8b98-2b9c5cf0f8c5.png)
![image](https://user-images.githubusercontent.com/12635915/88946401-36b75f00-d25d-11ea-8df5-9ec0ce62234e.png)

This makes it difficult to track a specific line through the animation.

**Comment by wadefagen** [comment]
Thanks for this observation!

I've just modified the code to ensure that the non-highlighted colors stay the same throughout an animation which definitely improves the animation! 🎉
