### ISSUE TITLE
Feature Request: Categorization of state with mask orders

### ISSUE THREAD

**Issue by kidinthehall** [wadefagen/91-DIVOC#58]
Using a time series of when states choose to mandate mask, classify the case, deaths, and fatality into mask and non-mask required states.

Here is a zipped csv of each state when they mandated some type of mask regulation
[statemaskdate.zip](https://github.com/wadefagen/91-DIVOC/files/5002526/statemaskdate.zip)

Here is the source article I scraped for that info
https://www.aarp.org/health/healthy-living/info-2020/states-mask-mandates-coronavirus.html

**Comment by wadefagen** [comment]
Thanks for the great suggestion!

I'm keeping 91-DIVOC as "just the data".  As I did a deep dive into that data, I found that:
- The mask regulations differ dramatically between states: some are mere recommendations, others mandate masks only in certain locations, and some other states have the major cities with strong mask mandates but lack any state-wide mandate.
- Different sources list different states with "mask mandates".  There's not a wide-spread agreement here (this was true about stay-at-home orders back in March/April as well).

In an effort to keep the data just about the data, this won't be added.  However, you can highlight any number of states by using "+Add Additional Highlight" and one feature I'll be working on is the ability to add your own "Custom Aggregation".  With this, you can create a line for groups of states based on whatever category that interests you.

Thank you again for the suggestion! :)
