### ISSUE TITLE
Romania is not included in EU-27

### ISSUE THREAD

**Issue by matt-perrinel-enview** [wadefagen/91-DIVOC#63]
If you select only countries from European Union, you don't see Romania
http://91-divoc.com/pages/covid-visualization/?chart=countries-normalized&highlight=France&show=eu27&y=both&scale=linear&data=deaths-daily-7&data-source=jhu&xaxis=right&extra=#countries-normalized

There may be other countries missing, but Romania is the only obvious one (it is the country with the most death/capita in the EU by a wide margin).

**Comment by wadefagen** [comment]
Thanks -- there was a stray space in the list of EU countries that prevented Romania from being picked up by the filter.  It's now fixed and deployed: https://github.com/wadefagen/91-DIVOC/commit/4f3a5879538fcebfee484e91c4a1ec3293231a26
