### ISSUE TITLE
Coronavirus Contribution by State - static text despite "show" value.

### ISSUE THREAD

**Issue by giasi** [wadefagen/91-DIVOC#68]
Static text "in the United States" is a mismatch error when id="filter-chart-states" selection is not: <option value="us-states" selected>All</option>.
_
<img width="1128" alt="Screen Shot 2020-11-09 at 1 31 22 PM" src="https://user-images.githubusercontent.com/4064015/98581708-e1451200-228f-11eb-90e8-b7186ba181b8.png">
_

**Comment by wadefagen** [comment]
Great catch and huge thanks for the fantastic and detailed bug report -- I just fixed this to display "selected data" instead of "United States" when all states aren't selected. 🎉

Changes: https://github.com/wadefagen/91-DIVOC/commit/9cd8c40c0f658d8ea778bbbde8f976d0c8e5529f

**Comment by giasi** [comment]
Glad I could help! The visualizations on your site bring such needed clarity to a explaining the data to others. Thank *YOU* for such a great resource.
