### ISSUE TITLE
West Virginia seems to have bogus data for New Confirmed COVID-19 Cases per Day by States/Territories, normalized by population

### ISSUE THREAD

**Issue by loupiote** [wadefagen/91-DIVOC#72]
West Virginia seems to have bogus data for New Confirmed COVID-19 Cases per Day (1 week average) by States/Territories, normalized by population. Check out on the graph.

**Comment by wadefagen** [comment]
I took a look and didn't see anything, but looking back it looks like this has resolved itself, possibly a bad data point in the underlying data?  Let me know if you're still seeing something off. :)

**Comment by loupiote** [comment]
yeah, looks resolved today, thanks!
